spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/SpringBootKeycloak
            user-name-attribute: julien
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid

kafka:
  bootstrapAddress: http://localhost:9092

server.port: 8081