server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker

keycloak:
  realm: SpringBootKeycloak
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: users-microservice
  credentials:
    secret: 82Fsy7KCd3ay1FWRpm7AzNe45ycj3DRE
  use-resource-role-mappings: true
  bearer-only: true

kafka:
  bootstrapAddress: http://localhost:9092