server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker

keycloak:
  realm: users-microservice
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: client-users-microservice
  credentials:
    secret: bfgOuZgj7DM7hAHC9Q6UQYDjOcJGFRTR
  use-resource-role-mappings: true
  bearer-only: true

kafka:
  bootstrapAddress: http://localhost:9092